[package]
name = "prometeu-desktop"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.88"

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
tauri = { version = "=2.11.5", features = [] }
tauri-plugin-dialog = "=2.7.3"
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"

[target.'cfg(unix)'.dependencies]
libc = "=0.2.189"
